### ISSUE TITLE
[BUG] star overlaps with cat name

### ISSUE THREAD

**Issue by selkirks** [lillithrosepup/clangen#10]
**Type**: UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
on a cat's profile, the favorite star overlaps with their name

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. have a cat named algaeflood
2. go onto their profile

**Commit # or Game Version Number**: no clue

**Additional context**
Add any other context about the problem here.![image](https://github.com/ImLvna/clangen/assets/126827015/fe0f8ad1-57cf-40e8-9850-4d770e34a591)

**Screenshots**

**Comment by lillithrosepup** [comment]
Tracking this in #14
