### ISSUE TITLE
[BUG] text overlapping

### ISSUE THREAD

**Issue by selkirks** [lillithrosepup/clangen#11]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
with same sex kits off and trying to select 2 same gender cats to have kits in the mate screen, text overlaps

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. turn same sex kits off
2. try to set 2 same gender cats as mates
3. see

**Commit # or Game Version Number**: idek man

**Additional context**

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://github.com/ImLvna/clangen/assets/126827015/e15e39d6-01cc-45c4-8e19-0218e6dc7466)

**Comment by lillithrosepup** [comment]
Tracking this in #14
