### ISSUE TITLE
[BUG] commit # invisible

### ISSUE THREAD

**Issue by selkirks** [lillithrosepup/clangen#12]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
the commit id is invisible

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go to clangen web
2. see

**Commit # or Game Version Number**: man.

**Additional context**

**Screenshots**
![image](https://github.com/ImLvna/clangen/assets/126827015/7006b0cc-7f88-4822-b042-cc69279ecb13)

**Comment by lillithrosepup** [comment]
<img width="177" alt="image" src="https://github.com/ImLvna/clangen/assets/44179559/253a395d-16e4-4633-81f4-e08498ce365b">
its there for me, maybe we fixed it without realizing?
