### ISSUE TITLE
[BUG] No text in 'cat toggles' menu

### ISSUE THREAD

**Issue by Tilire** [lillithrosepup/clangen#13]
**Type**: 
- UI 

**Describe the bug**
There is no text in 'cat toggles' menu in the cat's profile, but checkboxes are still there

**Grade**: (only select one)
- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Go to cat's profile
2. Click on 'cat toggles'
3. No text is present

**Commit # or Game Version Number**: f1de5c8f

**Screenshots**
![image](https://github.com/ImLvna/clangen/assets/101945148/2c8b5ea9-6d69-4030-ad15-b44e69fd8a68)

**Comment by lillithrosepup** [comment]
@howlagon u fix it stupid idk whats wrong

**Comment by tailhaver** [comment]
Fixed by 63f7889!
