### ISSUE TITLE
[BUG] Seaon and moon widget won't appear

### ISSUE THREAD

**Issue by Tilire** [lillithrosepup/clangen#2]
**Type**:
UI

**Describe the bug**
Season and moon widget won't appear. However, the arrow near it appears just fine

**Grade**:
Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go to setting
2. Check 'show moons and seasons widget'
3. Go to camp/cat list/patrol page
4. No widget, only arrow

**Commit # or Game Version Number**: a0b2c83a

**Screenshots**
![Скриншот 26-04-2024 150038](https://github.com/ImLvna/clangen/assets/101945148/2632f2d7-51c1-473f-9897-8563b61c5d61)

**Comment by tailhaver** [comment]
Fixed by 02e7896.
