### ISSUE TITLE
Hunting patrol crash

### ISSUE THREAD

**Issue by ZrainydayXXX** [lillithrosepup/clangen#3]
**Type**: 
- Code - 

**Describe the bug**
Game crashed for a hunting patrol

**Grade**: 
- Game-breaking -
- 
**Reproduce**
-Send out a hunting patrol with 3 cats

**Patrol ID + Outcome Print (if applicable)**:
- No print. Console wouldn't even show up -

**Commit # or Game Version Number**: 
- a0b2c83a

**Additional context**
It crashed so severely that the option for the console didn't show up. Had to reload for anything to respond.

**Screenshots**
![image](https://github.com/ImLvna/clangen/assets/77426212/5de72e21-5a8d-4309-b90c-091ddddcc34d)

**Comment by lillithrosepup** [comment]
Fixed in da053b83e58e537183954c38336dc62b72c676c8!
