### ISSUE TITLE
Saving Game Then Reload Restart At 1 Moon

### ISSUE THREAD

**Issue by StrangexSnake** [lillithrosepup/clangen#4]
**Type**:
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
As the title said, I was on moon 4, seeing how the randomness of patrols was the same, I saved and then reloaded the site. This caused the save file to revert back to moon one and losing process (EXP on cats, adults reverting back to apps/kits)

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. Skip moons for a few times (you can go on patrols to allow exp to increase and some cats to age) 
2. Save
3. Reload the site and wait
4. Check to see if any process has reverted

**Patrol ID + Outcome Print (if applicable)**:
N/A

**Commit # or Game Version Number**: 
Web Build 61e72abb

**Additional context**
N/A

**Screenshots**

**Comment by lillithrosepup** [comment]
This was fixed riiight after you got the error, close enough that the commit # is titled "fix saving" :(
