### ISSUE TITLE
[BUG] Error when you try to switch Clans

### ISSUE THREAD

**Issue by KiraDragoness** [lillithrosepup/clangen#5]
**Type**: UI/Code

**Describe the bug**
When you try to switch Clans, there's a pop-up stating an error has ocurred, giving you the option of opening the console. If you don't open the console, the window changes to "idle" and the screen stays gray, forcing you to reload the page. Once you reload though, the current Clan has changed as normal.

**Grade**: Game breaking

**Reproduce**
Create and save a Clan, then create a second one an attempt to switch back to the first one.

**Commit # or Game Version Number**: 61e72abb

**Screenshots**
![image](https://github.com/ImLvna/clangen/assets/121829433/da564638-886f-4abd-821d-99e0939b4b03)

**Comment by lillithrosepup** [comment]
Fixed in 84456e6c35fe67a2a5b155c03d1b5125e8259a9e
