### ISSUE TITLE
Disappearing Buttons in Clan Focus

### ISSUE THREAD

**Issue by mycenachlorophos** [lillithrosepup/clangen#6]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
When clicking on the Warriors Den in order to change the Clan Focus, you'll find that the buttons are not there. Buttons can still be clicked, but without the image it's hard to find which one specifically.

**Grade**: (only select one)
Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Go to the Camp tab
2. Click on the Warriors Den button
3. See error

**Commit # or Game Version Number**: Web Build 61e72abb

**Additional context**
I'm using a PC and google, if that is information that is important!

**Screenshots**
<img width="934" alt="Screenshot 2024-04-26 at 7 41 02 AM" src="https://github.com/ImLvna/clangen/assets/124000379/f860f927-63d2-497a-9eb3-920444bf2976">

**Comment by tailhaver** [comment]
Fixed by 02e7896.
