### ISSUE TITLE
Many Missing Buttons

### ISSUE THREAD

**Issue by mycenachlorophos** [lillithrosepup/clangen#7]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
Numerous buttons on a cats personal tab are missing, making it difficult to see how to change certain things without having memorized the normal version!

**Grade**: (only select one)
- Important - The bug has a large affect on the gameplay, but is not urgent

**Reproduce**
1. Go to Cat List
2. Click on any cat
3. Open the personal tab

**Commit # or Game Version Number**: 61e72abb

**Additional context**
Using PC & Google

**Screenshots**
<img width="944" alt="Screenshot 2024-04-26 at 8 03 42 AM" src="https://github.com/ImLvna/clangen/assets/124000379/cefd53b3-be84-41ac-95ed-f3b1c59eaf56">
<img width="937" alt="Screenshot 2024-04-26 at 8 03 56 AM" src="https://github.com/ImLvna/clangen/assets/124000379/4eed20be-e9c3-43ac-8d5d-7560956fb36c">
<img width="948" alt="Screenshot 2024-04-26 at 8 04 10 AM" src="https://github.com/ImLvna/clangen/assets/124000379/ed649021-d9b3-4294-abc0-347d39ea52fb">

**Comment by lillithrosepup** [comment]
Tracking this in #15
