### ISSUE TITLE
[BUG] Credits hovers in wrong place

### ISSUE THREAD

**Issue by ChibiGalaxies** [lillithrosepup/clangen#8]
**Type**: 
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
Title kinda explains it. On Windows pc version the hovers that pop up over the credits in the settings to give credits to the people working on clangen are in the wrong place. They're a bit too far down and the box where the hover is is a bit too big. Extremely minor visual bug, most people won't notice it.

**Grade**: 
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go to 'settings'
2. Click on 'info'
3. Scroll down to 'with contributions from' section.
4. Hover over names.
5. See error

**Patrol ID + Outcome Print (if applicable)**: N/A

**Commit # or Game Version Number**: 51f96877

**Additional context**
The size of the hovers also causes them to leak off the names and down the menu, the last credit is several lines under the copyright message.
Can't really show it because neither of my screen capture methods show my mouse, but the mouse is hovering over Coffee's name in the first image, not Archanyhm's.
There's also a blank hover spot over Kori/Kittenvy's names, so potentially there's a missing hover there. 

**Screenshots**
![image](https://github.com/ImLvna/clangen/assets/141930464/cbc9a1ed-7f29-4f29-b77e-3f031d6144f4)
![image](https://github.com/ImLvna/clangen/assets/141930464/aa5979cb-b2ac-4935-aea2-e15838df8908)

**Comment by lillithrosepup** [comment]
Tracking this in #14
