### ISSUE TITLE
[BUG] med cat den arrows placed odd

### ISSUE THREAD

**Issue by selkirks** [lillithrosepup/clangen#9]
**Type**: UI

**Describe the bug**
medicine cat den arrow buttons placed oddly

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. Go to med cat den
2. see error

**Commit # or Game Version Number**: i wish i knew. its invisible

**Additional context**

**Screenshots**
If applicable, add screenshots to help explain your problem.![image](https://github.com/ImLvna/clangen/assets/126827015/6db85f82-3045-43f8-b4e9-9e05c9c017bc)

**Comment by lillithrosepup** [comment]
Tracking this in #14
